### ISSUE TITLE
大佬您好，请问该如何可视化出论文中的效果呢？可以放下可视化的代码吗

### ISSUE THREAD

**Issue by HsLOL** [wulele2/Detr-heat-map-visualization#3]
大佬可以上传一下如何将注意力图和带有检测框图片二者结合可视化的代码吗

**Comment by wulele2** [comment]
你直接在现有基础上画个框不就行了，或者你可以先画框然后在此基础上画注意力不就行了，代码中也有预测出的框，直接画就行了啊

**Comment by HsLOL** [comment]
感谢大佬的回复，目前我可以画出这种效果，但是不知道怎么把两个图做一个结合 :-(
大佬可以提供一下相关的代码吗？
感谢！


![image](https://user-images.githubusercontent.com/53011009/175797673-abf57577-ee7a-415c-aff0-3f238ea48409.png)

![image](https://user-images.githubusercontent.com/53011009/175797668-cd588b7c-bdc5-422b-a8ba-169732c40080.png)

**Comment by wulele2** [comment]
两个图结合应该是直接相加就行。有可能多做一步scale操作，我这科学上网有问题，改不了。

**Comment by HsLOL** [comment]
我这边尝试过直接相加
但是注意力图是小数构成的数组，原始图像是一个0-255的整数数组，所以无法直接相加;

下面展示的是直接imshow()的效果，大佬知道相关的将小数数组转换成0-255的相关函数吗

**Comment by wulele2** [comment]
乘255在取整试试

**Comment by HsLOL** [comment]
> 乘255在取整试试

好的，我再尝试一下，谢谢大佬

**Comment by Jasper0068** [comment]
> 感谢大佬的回复，目前我可以画出这种效果，但是不知道怎么把两个图做一个结合 :-( 大佬可以提供一下相关的代码吗？ 感谢！
> 
> ![image](https://user-images.githubusercontent.com/53011009/175797673-abf57577-ee7a-415c-aff0-3f238ea48409.png)
> 
> ![image](https://user-images.githubusercontent.com/53011009/175797668-cd588b7c-bdc5-422b-a8ba-169732c40080.png)

您好方便介绍一下您的这种效果图 代码吗
